# Exercises week 1
## 2.1.8.1

In [1]:
from mxnet import np, npx
npx.set_np()

In [10]:
X = np.arange(12).reshape(3, 4)
Y = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
np.concatenate([X, Y], axis=0), np.concatenate([X, Y], axis=1)
print(X)
print(Y)
print(X == Y)
print(X < Y)
print(X > Y)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
[[False  True False  True]
 [False False False False]
 [False False False False]]
[[ True False  True False]
 [False False False False]
 [False False False False]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


If we use X < Y or X > Y, instead of X == Y, the resulting tensor becomes different, because each element in the resulting tensor is based on the comparison between the two source tensors.

## 2.1.8.2

In [25]:
a = np.arange(3).reshape(3, 1)
b = np.arange(2).reshape(1, 2)
a = np.arange(3).reshape(3, 1)
b = np.arange(3).reshape(1, 3)
#a = np.random.normal(0, 1, size=(3, 3))
#b = np.random.normal(0, 1, size=(3, 3))
a, b

(array([[0.],
        [1.],
        [2.]]),
 array([[0., 1.]]))

In [26]:
a + b

array([[0., 1.],
       [1., 2.],
       [2., 3.]])

If we replace these tensors by 3 dimensional tensors, we get a three dimensional tensor back, this follows from the properties of matrices.

## 2.2.5 (1 and 2)

In [35]:
import os
import random

os.makedirs(os.path.join('.', 'data'), exist_ok=True)
data_file = os.path.join('.', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # Column names
    for i in range(0,100):
        entry = ''
        flip = random.randint(0, 1)
        if (flip == 0):
            entry += 'NA,'
        else:
            entry += str(random.randint(0,7)) + ','
        flip = random.randint(0,1)
        if (flip == 0):
            entry += 'Pave,'
        else:
            entry += 'NA,'
        entry += str(random.randint(100000,200000)) + '\n'
        f.write(entry)

import pandas as pd

data = pd.read_csv(data_file)
print(data)

cols = [data.iloc[:, 0].isna().sum(), data.iloc[:, 1].isna().sum()]
data = data.drop(data.columns[cols.index(max(cols))], axis=1)
if (data.columns[0] == 'NumRooms'):
    data = data.fillna(0)
else:
    data = pd.get_dummies(data, dummy_na=True)

print(data)
X = np.array(data)
X

    NumRooms Alley   Price
0        NaN  Pave  170922
1        NaN   NaN  157307
2        NaN  Pave  116050
3        NaN   NaN  126622
4        NaN   NaN  127878
..       ...   ...     ...
95       NaN   NaN  131340
96       3.0  Pave  170906
97       1.0  Pave  162121
98       NaN  Pave  162252
99       NaN  Pave  188424

[100 rows x 3 columns]
     Price  Alley_Pave  Alley_nan
0   170922           1          0
1   157307           0          1
2   116050           1          0
3   126622           0          1
4   127878           0          1
..     ...         ...        ...
95  131340           0          1
96  170906           1          0
97  162121           1          0
98  162252           1          0
99  188424           1          0

[100 rows x 3 columns]


array([[1.70922e+05, 1.00000e+00, 0.00000e+00],
       [1.57307e+05, 0.00000e+00, 1.00000e+00],
       [1.16050e+05, 1.00000e+00, 0.00000e+00],
       [1.26622e+05, 0.00000e+00, 1.00000e+00],
       [1.27878e+05, 0.00000e+00, 1.00000e+00],
       [1.55627e+05, 1.00000e+00, 0.00000e+00],
       [1.66141e+05, 1.00000e+00, 0.00000e+00],
       [1.87854e+05, 1.00000e+00, 0.00000e+00],
       [1.83804e+05, 1.00000e+00, 0.00000e+00],
       [1.82898e+05, 0.00000e+00, 1.00000e+00],
       [1.42542e+05, 1.00000e+00, 0.00000e+00],
       [1.93442e+05, 0.00000e+00, 1.00000e+00],
       [1.00018e+05, 1.00000e+00, 0.00000e+00],
       [1.89532e+05, 1.00000e+00, 0.00000e+00],
       [1.32358e+05, 0.00000e+00, 1.00000e+00],
       [1.04663e+05, 1.00000e+00, 0.00000e+00],
       [1.16299e+05, 1.00000e+00, 0.00000e+00],
       [1.86378e+05, 1.00000e+00, 0.00000e+00],
       [1.55318e+05, 1.00000e+00, 0.00000e+00],
       [1.22030e+05, 1.00000e+00, 0.00000e+00],
       [1.12839e+05, 0.00000e+00, 1.0000

## 2.3.13.1
Suppose we have a matrix $A$. Then for $A^T$, $a^T_{ij} = a_{ji}$. If we then take $(A^T)^T$, we have that $(a^T)^T_{ij} = a^T_{ji} = a_{ij}$. Because of this it follows that $(A^T)^T = A$.

## 2.3.13.2

Suppose we have two $m$ x $n$ matrices $A$ and $B$. <br>
We have, by definition that for $A^T, a^T_{mn} = a_{nm}$, and analogously for $B^T$. <br>
We then have $A^T + B^T = \forall_{mn} a_{nm} + b_{nm} = \forall_{mn} a^T_{mn} + b^T_{mn} = (A + B)^T$. <br>
This shows that indeed $A^T + B^T = (A + B)^T$.

## 2.3.13.3

Yes. <br>
We have that:
* $(A^T)^T = A$ 
* $(A + B)^T = A^T + B^T$


If we have $X = A^T + A$, we have $X^T = (A^T + A)^T = (A^T + (A^T)^T)^T = (A^T)^T + A^T = A^T + A = X$. 




## 2.4.6.1

![Image](./images/tangent_w1_calc.png)

## 2.4.6.2

In this function, there are two variables, and the gradient is a vector containing the all the partial derivatives with respect to all variables in the function. So, the gradient of $f(x) = [6x_1, 5e^{x_2}]$.

## 2.4.6.3

Since $\parallel x \parallel_2 = \sqrt{x^2_1 + \dots + x^2_n}$, the gradient of $f(x) = \langle \frac{x_1}{\sqrt{x^2_1 + \dots + x^2_n}},\dots,\frac{x_n}{\sqrt{x^2_1 + \dots + x^2_n}} \rangle$

## 2.4.6.4

$\frac{\partial u}{\partial a} = \frac{\partial u}{\partial x}\frac{\partial x}{\partial a} + \frac{\partial u}{\partial y}\frac{\partial y}{\partial a} + \frac{\partial u}{\partial z}\frac{\partial z}{\partial a}$, and analogously for $b$.

## 2.5.6.1

The computational graph will increase in size exponentially. For each partial derivative in the gradient (which contains all first derivatives), we get another chain of partial derivatives.

## 2.5.6.2



In [46]:
from mxnet import autograd

x = np.arange(4.0)
x.attach_grad()

with autograd.record():
    y = 2 * np.dot(x, x)
y

In [50]:
y.backward(retain_graph=True)
x.grad

array([ 0.,  4.,  8., 12.])

We see that if we run the function again, we get an error, because the computational graph is not retained in memory. We can set the parameter `retain_graph` to `True` to prevent this error, but then the result is the same every time.